### ISSUE TITLE
File "/usr/lib/python3.5/json/decoder.py", line 339, in decode     obj, end = self.raw_decode(s, idx=_w(s, 0).end())   File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode     raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Rishan123** [mrpjevans/tradfri-fun#1]
when I type: python3 -i -m pytradfri XXX.XXX.X.XXX,
I get the error:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 48, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 90, in _execute
    api_command.result = _process_output(return_value, parse_json)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 195, in _process_output
    return json.loads(output)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by mrpjevans** [comment]
You need to replace the XXXs with the IP address of your Tradfri gateway
